{{- if .Values.web.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-secrets" $.Release.Name | replace "_" "-" | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
{{- range $key, $val := .Values.web.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
