# Default values for web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  tag: ""


# port
#
# define the port to access of the pod so the service knows which port to access
port: 8080

web:
  # arguments
  #
  # An array of arguments which can be used to override the default command
  #
  # arguments:
  #  - "example-cron"
  #  - "--log"
  #  - "info"

  arguments: []

  #  secrets
  #
  # An array of secret environment variables that should be available from within the job.
  #
  #
  # Docs: https://github.com/bitnami-labs/sealed-secrets#usage
  #
  # secrets:
  #   HELLO_YOU: "< Kubeseal encrypted value>"
  #   THE_SECRET_TO_LIFE: "< Kubeseal encrypted value>"
  secrets: {}
