# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Install Dev tools
        run: sudo apt-get update && sudo apt-get install -y jq libjq-dev
      - name: Install Helm
        run: |
          export HELM_PACKAGE=helm-v3.3.0-linux-amd64.tar.gz
          wget https://get.helm.sh/$HELM_PACKAGE
          tar -zxvf $HELM_PACKAGE
          sudo mv linux-amd64/helm /usr/local/bin/helm
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: |
          export RUBYJQ_USE_SYSTEM_LIBRARIES=1
          bundle install
      - name: Run tests
        run: script/test
